/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.cabolabs.edu.openehr.templates

import picocli.CommandLine
import picocli.CommandLine.Command
import picocli.CommandLine.Option
import picocli.CommandLine.Parameters
import java.nio.file.Path

@Command
class App {

   static void main(String[] args)
   {
      int rc = new CommandLine(new App()).execute(args)
      System.exit(rc)
   }

   @Command(
      name = 'parse',
      description = 'Parses a given template in OPT format'
   )
   public void parseCommand(
      @Parameters(arity = "1") Path pathToOpt
   )
   {
      def opt = Services.parse(pathToOpt)

      if (opt)
      {
         println "Template parsed correctly."
         println "Template ID = "+ opt.templateId
         println "Concept = "+ opt.concept
      }
   }

   @Command(
      name = 'traverse',
      description = 'Traverses a given template in OPT format'
   )
   public void traverseCommand(
      @Parameters(arity = "1") Path pathToOpt
   )
   {
      def opt = Services.traverse(pathToOpt)
   }
}